### ISSUE TITLE
Add a run_constrained for libopenblas on openblas.

### ISSUE THREAD

**Issue by isuruf** [conda-forge/openblas-feedstock#71]
To avoid `libopenblas 0.3.6` and `openblas 0.3.5` being installable in the same environment.

**Comment by ocefpaf** [comment]
@isuruf we have:

```yaml
  - name: openblas
    ...
    requirements:
      run:
        - {{ pin_subpackage("libopenblas", exact=True) }}
```

Isn't that enough? Or should we do:

```yaml
  - name: openblas
    ...
    requirements:
      run:
        - {{ pin_subpackage("libopenblas", exact=True) }}
      run_constrained:
        - libopenblas =={{ version }}
```
